# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b18df40778430d47427f61367779f82c3a5aa4a7206df59e46a4ca980ae82125f5e970709fbb8909a2df7024e1c2169b537d4563c553772be0f6d2924cc58de5

test:
  secret_key_base: 1fdb616b941e6e9b0f89c3249e9f0c73352a48de160be25b2603567a5cdd015eb2d5ed2acf3764ef67108a3d47c614f41c57a297314fd3461837b6f5eac1c322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
